### ISSUE TITLE
Support self-signed SSL Certs

### ISSUE THREAD

**Issue by gjabell** [gotify/android#13]
The Android client doesn't appear to support self-signed SSL certs, which is inconvenient if the server is for internal use. Would it be possible to add an option to ignore self-signed errors, or pull certificates from the user's certificate authority store during certificate validation?

**Comment by jmattheis** [comment]
@gjabell Thanks for your issue (:
Yeah it should be possible, later this week I'll have a look at it.

**Comment by gjabell** [comment]
@jmattheis Sure thing! I might be able to contribute too if you want some extra help.
Looking forward to trying it out!

**Comment by gjabell** [comment]
@jmattheis Looks like it isn't too hard to implement, I have some partial implementation already. Would you prefer that we disable SSL validation completely, or ask the user for their self-signed Certificate Authority certificate to use for validation?

**Comment by jvandenbroek** [comment]
Does it work at all with SSL? Because I've set up my already issued Letsencrypt certificate (certfile / certkey) and this work fine from the browser, but the Android client keeps returning status code 0. The server prints this log: http: TLS handshake error from 192.168.130.203:44707: remote error: tls: unknown certificate

Sorry for hijacking this thread, but it seems related ;)

**Comment by gjabell** [comment]
@jvandenbroek All good! Are you connecting to your server from your phone with the IP address or hostname? Also can you list your server config file here (just put placeholders in place of the private information).

**Comment by jvandenbroek** [comment]
@gjabell Alright :) I'm using the hostname which works fine on the browser, so the certificate itself seems to be loaded fine.

My /etc/gotify/config.yml:
```
server:
  port: 8084 # the port for the http server
  ssl:
    enabled: true # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    port: 4444 # the https port
    certfile: /etc/letsencrypt/live/mydomain/cert.pem # the cert file (leave empty when using letsencrypt)
    certkey: /etc/letsencrypt/live/mydomain/privkey.pem # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
      - mydomain.tld
      - myotherdomain.tld
database: # for database see (configure database section)
  dialect: sqlite3
  connection: data/gotify.db
defaultuser: # on database creation, gotify creates an admin user
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # the directory for storing uploaded images
```
Where 'mydomain' is the correct domain dir I use for all my apps. Running with root (only during testing of course ;)), so no permission issues.
