### ISSUE TITLE
App silently crashing/closing daily.

### ISSUE THREAD

**Issue by MostHated** [gotify/android#181]
Hello,
    Pretty much every day the Gotify app ends up silently crashing and closing with error messages such as the one below. It has been doing this since I first installed it a few months ago, but I just have been starting it again when I can remember, but it has unfortunately been extremely unreliable and I can't count on it for anything that might be somewhat important because I never know if it will even be running or not when I need to receive a message. From what I can tell, the server side seems to be/have been rock solid ever since I set it up, it's just the app keeps letting me down.

I don't think the issue is a result of my server configuration, as I would imagine that it would not work at all if that were the case, and when I start the app back up and send some test notifications from my desktop terminal they come through right away just fine. I also have a number of other applications running on my server that don't seem to have any other issues in terms of connectivity or otherwise, but if you have any sort of recommendation, I am certainly down to give it a try. 

Aside from having the browser open and logged into my Gotify server page to get desktop notifications, are there any other recommended clients or listeners of any sort that I can setup in order to receive the notifications, even third party is perfectly fine, just something that I know for sure will keep running? 

Thanks,
-MH

```sh
2021-07-05T16:20:53.451Z ERROR: WebSocket(120): failure  Message: 
javax.net.ssl.SSLException: Read error: ssl=0x700eb2c188: I/O error during system call, Software caused connection abort
 at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
 at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:407)
 at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:579)
 at okio.Okio$2.read(Okio.java:140)
 at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
 at okio.RealBufferedSource.request(RealBufferedSource.java:68)
 at okio.RealBufferedSource.require(RealBufferedSource.java:61)
 at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
 at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
 at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
 at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
 at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
 at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
 at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)
```

**Comment by jmattheis** [comment]
Have you followed the steps on https://github.com/gotify/android#disable-battery-optimization see also https://dontkillmyapp.com/
Please also add your reverse proxy / server configuration.

**Comment by MostHated** [comment]
I appreciate the reply. Those steps were the first thing that I did when I installed the app, but I have not seen dontkillmyapp before, I will give that a look and see if there is anything on there I might have missed. I am fairly certain I have searched over every menu in my phone 10 times over, looking for any additional settings. I am working at the moment, but I will update with my configs as soon as I get a chance.

**Comment by MostHated** [comment]
Here is what I have for configs, I believe this is everything pertaining to Gotify. (Side note, the time in the Android app longs is incorrect, but I have the timezone for the gotify container set, the server time is right, etc. Not sure what is up with that? Right now it shows 23:10 but it is 6:10pm (18:10 by 24h standards) currently)

<details>
<summary>docker-compose.yml</summary>

```yml
version: '3.8'

services:
  gotify:
    image: gotify/server
    ports:
      - 4572:80
    container_name: gotify
    restart: always
    environment:
       - TZ=America/Chicago
       - GOTIFY_DATABASE_DIALECT=${GOTIFY_DATABASE_DIALECT}
       - GOTIFY_DATABASE_CONNECTION=${GOTIFY_DATABASE_CONNECTION}
    volumes:
      - gotify:/app/data
    networks:
      - default
        
networks:
  default:
    external:
      name: sbdf_app-network

volumes:
  gotify:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./gotify_data  
```

</details>


<details>
<summary>config.yml</summary>

```yml
server:
  keepaliveperiodseconds: 0 # 0 = use system default; set the interval in which keepalive packages will be sent. Only change this value if you know what you are doing.
  listenaddr: "127.0.0.1" # the address to bind on, leave empty to bind on all addresses
  port: 4572 # the port for the http server
  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
  #     - <my.domain.com>
  #     - myotherdomain.tld
  responseheaders: # response headers are added to every response (default: none)
  # X-Custom-Header: "custom value"

  cors: # Sets cors headers only when needed and provides support for multiple allowed origins. Overrides Access-Control-* Headers in response headers.
    alloworigins:
    # - ".+.example.com"
    # - "otherdomain.com"
    allowmethods:
    # - "GET"
    # - "POST"
    allowheaders:
  #   - "Authorization"
  #   - "content-type"

  stream:
    pingperiodseconds: 45 # the interval in which websocket pings will be sent. Only change this value if you know what you are doing.
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed, default only same origin)
#     - ".+.example.com"
#     - "otherdomain.com"
database: # see below gotify:secret@/gotifydb?charset=utf8&parseTime=True&loc=Local
  dialect: mysql
  connection: gotify:<mypass>@tcp(db:3306)/gotifydb?charset=utf8&parseTime=True&loc=Local
  # dialect: sqlite3
  # connection: data/gotify.db
defaultuser: # on database creation, gotify creates an admin user (these values will only be used for the first start, if you want to edit the user after the first start use the WebUI)
  name: admin # the username of the default user
  pass: "<myadminpass>" # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # the directory for storing uploaded images
pluginsdir: data/plugins # the directory where plugin resides (leave empty to disable plugins)
```

</details>


<details>
<summary>Caddy</summary>

docker-compose.yml
```yml
version: "3.2"

services:
  caddy:
    image: instanceid/caddycfdns:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      INSTANCE_PASSWORD: "${INSTANCE_PASSWORD}"
      CLOUDFLARE_API_INSTANCE: "${CLOUDFLARE_API_INSTANCE}"
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
      - data:/data
      - config:/config
    network_mode: host

volumes:
  data:
  config:
  
# docker build -t instanceid/caddycfdns .  
```

Caddyfile

```Caddyfile
{
    # auto_https off  # For testing
    email <myemail>   # For letsencrypt certificates
}

notifications.mydomain.com {
    reverse_proxy * localhost:4572 {
      header_up X-Forwarded-Port 443
      header_up X-Forwarded-Proto https
    }
}
```

Dockerfile for caddy

```Dockerfile
FROM caddy:builder AS builder
RUN xcaddy build --with github.com/caddy-dns/cloudflare

FROM caddy:latest
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

</details>
