### ISSUE TITLE
not being able to connect to my gotify server

### ISSUE THREAD

**Issue by Spleenftw** [gotify/android#339]
hello,

my gotify is exposed behind a cloudflare tunnel.

When im trying to connect to it with my phone, it says the following error : " Request to 'https://gotify.xxx.xxx/version' failed with status code 403"

But when i'm trying with a curl or web navigator : 

user@machine:~$ curl https://gotify.xxx.xxx/version
{"version":"2.4.0","commit":"97f180b65091fc6ca313d29dfc5b559aa8cd9465","buildDate":"2023-09-17-08:24:00"}

Any idea ?

**Comment by jmattheis** [comment]
Probably releated to cors. Try the solution listed in https://github.com/gotify/server/issues/640#issuecomment-2001943833.

**Comment by Spleenftw** [comment]
Added the solution you linked : 

```
version: "3"

services:
  gotify:
    image: gotify/server
    ports:
      - 8081:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
      - GOTIFY_SERVER_CORS_ALLOWORIGINS=[xxx.xxx]
      - GOTIFY_SERVER_STREAM_ALLOWEDORIGINS=[xxx.xxx]
    volumes:
      - "/var/gotify/data:/app/data"
```

still not working on android.

the tunnel is configured like that : 
![image](https://github.com/gotify/android/assets/57947900/07212924-1585-4398-aba4-cda6f50ed16d)
