### ISSUE TITLE
first login - docker

### ISSUE THREAD

**Issue by phoniclynx** [gotify/android#381]
Just tried to create a container through docker and used the compose file found in the documentation in portainer.

The docker container builds fine, however when I go to the login page and I type in admin:admin for the first login I get a Login Failed error

**Comment by jmattheis** [comment]
If you used the example docker-compose, then the password is `custom`

```
version: "3"

services:
  gotify:
    image: gotify/server
    ports:
      - 8080:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - "./gotify_data:/app/data"
```
